name: Bundle Size PR Check

on:
  pull_request:
    branches: ["main", "master"]
    paths:
      - "FrontEnd/my-app/**"
      - "package.json"
      - "package-lock.json"

jobs:
  bundle-size:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Remove package-lock and node_modules
        run: |
          rm -rf ./FrontEnd/my-app/package-lock.json
          rm -rf ./FrontEnd/my-app/node_modules

      - name: Install dependencies
        working-directory: ./FrontEnd/my-app
        run: npm install

      - name: Check Bundle Size Regression
        uses: preactjs/compressed-size-action@v2
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          build-script: "build"
          cwd: "./FrontEnd/my-app"
          pattern: ".next/**/*.{js,css,html}"
          exclude: "{**/*.map,**/node_modules/**}"
          minimum-change-threshold: 100
