import {
  AssembledTransaction,
  Client as ContractClient,
} from '@stellar/stellar-sdk/contract';
import { Address } from '@stellar/stellar-sdk';

export { AssembledTransaction } from '@stellar/stellar-sdk/contract';

// ─────────────────────────────────────────────────────────────────────────────
// Enums
// ─────────────────────────────────────────────────────────────────────────────

export enum QuestStatus {
  Active = 'Active',
  Paused = 'Paused',
  Completed = 'Completed',
  Expired = 'Expired',
  Cancelled = 'Cancelled',
}

export enum SubmissionStatus {
  Pending = 'Pending',
  Approved = 'Approved',
  PartiallyPaid = 'PartiallyPaid',
  Rejected = 'Rejected',
  Paid = 'Paid',
}

export enum DisputeStatus {
  Pending = 'Pending',
  UnderReview = 'UnderReview',
  Resolved = 'Resolved',
  Withdrawn = 'Withdrawn',
  Appealed = 'Appealed',
}

export enum Role {
  SuperAdmin = 'SuperAdmin',
  Admin = 'Admin',
  Pauser = 'Pauser',
  OracleAdmin = 'OracleAdmin',
  StatsAdmin = 'StatsAdmin',
  BadgeAdmin = 'BadgeAdmin',
}

export enum Badge {
  Rookie = 'Rookie',
  Explorer = 'Explorer',
  Veteran = 'Veteran',
  Master = 'Master',
  Legend = 'Legend',
}

export enum OracleType {
  StellarAsset = 'StellarAsset',
  StellarOracle = 'StellarOracle',
  Custom = 'Custom',
}

// ─────────────────────────────────────────────────────────────────────────────
// Interfaces
// ─────────────────────────────────────────────────────────────────────────────

export interface Quest {
  id: string;
  creator: string;
  reward_asset: string;
  reward_amount: bigint;
  verifier: string;
  deadline: bigint;
  status: QuestStatus;
  total_claims: number;
}

export interface Submission {
  quest_id: string;
  submitter: string;
  proof_hash: string;
  status: SubmissionStatus;
  claimed_amount: bigint;
  timestamp: bigint;
}

export interface Dispute {
  quest_id: string;
  initiator: string;
  arbitrator: string;
  status: DisputeStatus;
  filed_at: bigint;
}

export interface Commitment {
  hash: string;
  timestamp: bigint;
}

export interface UserCore {
  xp: bigint;
  level: number;
  quests_completed: number;
}

export interface UserBadges {
  badges: Badge[];
}

export interface BadgeType {
  id: string;
  name: string;
  description: string;
  xp_reward: bigint;
}

export interface EscrowInfo {
  quest_id: string;
  depositor: string;
  token: string;
  total_deposited: bigint;
  total_paid_out: bigint;
  total_refunded: bigint;
  is_active: boolean;
  created_at: bigint;
  deposit_count: number;
}

export interface QuestMetadata {
  title: string;
  description: string;
  requirements: string[];
  category: string;
  tags: string[];
}

export interface VerifierStake {
  token: string;
  amount: bigint;
  is_active: boolean;
}

export interface PlatformStats {
  total_quests_created: bigint;
  total_submissions: bigint;
  total_rewards_distributed: bigint;
  total_active_users: bigint;
  total_rewards_claimed: bigint;
}

export interface CreatorStats {
  quests_created: number;
  total_rewards_posted: bigint;
  total_submissions_received: number;
  total_claims_paid: number;
  reputation_score: number;
}

export interface BatchQuestInput {
  id: string;
  reward_asset: string;
  reward_amount: bigint;
  verifier: string;
  deadline: bigint;
}

export interface BatchApprovalInput {
  quest_id: string;
  submissions: string[];
}

export interface PriceData {
  base_asset: string;
  quote_asset: string;
  price: bigint;
  decimals: number;
  timestamp: bigint;
  confidence: number;
}

export interface OracleConfig {
  oracle_address: string;
  oracle_type: OracleType;
  max_age_seconds: bigint;
  min_confidence: number;
  is_active: boolean;
}

export interface AggregatedPrice {
  base_asset: string;
  quote_asset: string;
  weighted_price: bigint;
  decimals: number;
  sources_used: number;
  total_sources: number;
  confidence_score: number;
  timestamp: bigint;
}

// ─────────────────────────────────────────────────────────────────────────────
// Client — dynamic methods (delegated to ContractClient generated by spec)
// ─────────────────────────────────────────────────────────────────────────────

export interface StellarEarnOptions {
  rpcUrl: string;
  contractId: string;
  networkPassphrase?: string;
}

export class StellarEarn {
  private client: any = null;
  public readonly contractId: string;
  public readonly rpcUrl: string;
  public readonly networkPassphrase: string;

  constructor(options: StellarEarnOptions) {
    this.contractId = options.contractId;
    this.rpcUrl = options.rpcUrl;
    this.networkPassphrase =
      options.networkPassphrase ?? 'Test SDF Network ; September 2015';
  }

  async connect(): Promise<void> {
    const { Client } = await import('@stellar/stellar-sdk/contract');
    this.client = await Client.from({
      rpcUrl: this.rpcUrl,
      contractId: this.contractId,
      networkPassphrase: this.networkPassphrase,
    });
  }

  private get c(): any {
    if (!this.client) {
      throw new Error('StellarEarn not connected. Call await client.connect() first.');
    }
    return this.client;
  }

  initialize(
    args: { admin: string },
    opts?: any,
  ): AssembledTransaction<void> {
    return this.c.initialize([new Address(args.admin)], opts);
  }

  authorize_upgrade(
    args: { caller: string },
    opts?: any,
  ): AssembledTransaction<void> {
    return this.c.authorize_upgrade([new Address(args.caller)], opts);
  }

  get_version(opts?: any): AssembledTransaction<number> {
    return this.c.get_version(undefined, opts);
  }

  get_admin(opts?: any): AssembledTransaction<string> {
    return this.c.get_admin(undefined, opts);
  }

  get_config(opts?: any): AssembledTransaction<Array<[string, string]>> {
    return this.c.get_config(undefined, opts);
  }

  add_admin(
    args: { caller: string; new_admin: string },
    opts?: any,
  ): AssembledTransaction<void> {
    return this.c.add_admin(
      [new Address(args.caller), new Address(args.new_admin)],
      opts,
    );
  }

  remove_admin(
    args: { caller: string; admin_to_remove: string },
    opts?: any,
  ): AssembledTransaction<void> {
    return this.c.remove_admin(
      [new Address(args.caller), new Address(args.admin_to_remove)],
      opts,
    );
  }

  grant_role(
    args: { caller: string; address: string; role: Role },
    opts?: any,
  ): AssembledTransaction<void> {
    return this.c.grant_role(
      [new Address(args.caller), new Address(args.address), args.role],
      opts,
    );
  }

  revoke_role(
    args: { caller: string; address: string; role: Role },
    opts?: any,
  ): AssembledTransaction<void> {
    return this.c.revoke_role(
      [new Address(args.caller), new Address(args.address), args.role],
      opts,
    );
  }

  has_role(
    args: { address: string; role: Role },
    opts?: any,
  ): AssembledTransaction<boolean> {
    return this.c.has_role([new Address(args.address), args.role], opts);
  }

  is_admin(
    args: { address: string },
    opts?: any,
  ): AssembledTransaction<boolean> {
    return this.c.is_admin([new Address(args.address)], opts);
  }

  register_quest(
    args: {
      id: string;
      creator: string;
      reward_asset: string;
      reward_amount: bigint;
      verifier: string;
      deadline: bigint;
    },
    opts?: any,
  ): AssembledTransaction<void> {
    return this.c.register_quest(
      [
        args.id,
        new Address(args.creator),
        new Address(args.reward_asset),
        args.reward_amount,
        new Address(args.verifier),
        args.deadline,
      ],
      opts,
    );
  }

  register_quest_with_metadata(
    args: {
      id: string;
      creator: string;
      reward_asset: string;
      reward_amount: bigint;
      verifier: string;
      deadline: bigint;
      metadata: QuestMetadata;
    },
    opts?: any,
  ): AssembledTransaction<void> {
    return this.c.register_quest_with_metadata(
      [
        args.id,
        new Address(args.creator),
        new Address(args.reward_asset),
        args.reward_amount,
        new Address(args.verifier),
        args.deadline,
        args.metadata,
      ],
      opts,
    );
  }

  register_quests_batch(
    args: { creator: string; quests: BatchQuestInput[] },
    opts?: any,
  ): AssembledTransaction<void> {
    return this.c.register_quests_batch(
      [new Address(args.creator), args.quests],
      opts,
    );
  }

  pause_quest(
    args: { caller: string; quest_id: string },
    opts?: any,
  ): AssembledTransaction<void> {
    return this.c.pause_quest([new Address(args.caller), args.quest_id], opts);
  }

  resume_quest(
    args: { caller: string; quest_id: string },
    opts?: any,
  ): AssembledTransaction<void> {
    return this.c.resume_quest(
      [new Address(args.caller), args.quest_id],
      opts,
    );
  }

  commit_submission(
    args: { quest_id: string; submitter: string; commitment_hash: string },
    opts?: any,
  ): AssembledTransaction<void> {
    return this.c.commit_submission(
      [args.quest_id, new Address(args.submitter), args.commitment_hash],
      opts,
    );
  }

  reveal_submission(
    args: {
      quest_id: string;
      submitter: string;
      proof_hash: string;
      salt: string;
    },
    opts?: any,
  ): AssembledTransaction<void> {
    return this.c.reveal_submission(
      [
        args.quest_id,
        new Address(args.submitter),
        args.proof_hash,
        args.salt,
      ],
      opts,
    );
  }

  submit_proof(
    args: { quest_id: string; submitter: string; proof_hash: string },
    opts?: any,
  ): AssembledTransaction<void> {
    return this.c.submit_proof(
      [args.quest_id, new Address(args.submitter), args.proof_hash],
      opts,
    );
  }

  approve_submission(
    args: { quest_id: string; submitter: string; verifier: string },
    opts?: any,
  ): AssembledTransaction<void> {
    return this.c.approve_submission(
      [
        args.quest_id,
        new Address(args.submitter),
        new Address(args.verifier),
      ],
      opts,
    );
  }

  approve_submissions_batch(
    args: { verifier: string; submissions: BatchApprovalInput[] },
    opts?: any,
  ): AssembledTransaction<void> {
    return this.c.approve_submissions_batch(
      [new Address(args.verifier), args.submissions],
      opts,
    );
  }

  claim_reward(
    args: { quest_id: string; submitter: string; amount: bigint },
    opts?: any,
  ): AssembledTransaction<void> {
    return this.c.claim_reward(
      [args.quest_id, new Address(args.submitter), args.amount],
      opts,
    );
  }

  get_user_stats(
    args: { user: string },
    opts?: any,
  ): AssembledTransaction<UserCore> {
    return this.c.get_user_stats([new Address(args.user)], opts);
  }

  get_user_badges(
    args: { user: string },
    opts?: any,
  ): AssembledTransaction<UserBadges> {
    return this.c.get_user_badges([new Address(args.user)], opts);
  }

  grant_badge(
    args: { admin: string; user: string; badge: Badge },
    opts?: any,
  ): AssembledTransaction<void> {
    return this.c.grant_badge(
      [new Address(args.admin), new Address(args.user), args.badge],
      opts,
    );
  }

  register_badge_type(
    args: { caller: string; badge_type: BadgeType },
    opts?: any,
  ): AssembledTransaction<void> {
    return this.c.register_badge_type(
      [new Address(args.caller), args.badge_type],
      opts,
    );
  }

  update_badge_type(
    args: { caller: string; badge_type: BadgeType },
    opts?: any,
  ): AssembledTransaction<void> {
    return this.c.update_badge_type(
      [new Address(args.caller), args.badge_type],
      opts,
    );
  }

  remove_badge_type(
    args: { caller: string; id: string },
    opts?: any,
  ): AssembledTransaction<void> {
    return this.c.remove_badge_type([new Address(args.caller), args.id], opts);
  }

  get_badge_type(
    args: { id: string },
    opts?: any,
  ): AssembledTransaction<BadgeType> {
    return this.c.get_badge_type([args.id], opts);
  }

  list_badge_types(opts?: any): AssembledTransaction<BadgeType[]> {
    return this.c.list_badge_types(undefined, opts);
  }

  open_dispute(
    args: { quest_id: string; initiator: string; arbitrator: string },
    opts?: any,
  ): AssembledTransaction<Dispute> {
    return this.c.open_dispute(
      [args.quest_id, new Address(args.initiator), new Address(args.arbitrator)],
      opts,
    );
  }

  resolve_dispute(
    args: {
      quest_id: string;
      initiator: string;
      arbitrator: string;
      upheld: boolean;
      slash_bps: number;
    },
    opts?: any,
  ): AssembledTransaction<void> {
    return this.c.resolve_dispute(
      [
        args.quest_id,
        new Address(args.initiator),
        new Address(args.arbitrator),
        args.upheld,
        args.slash_bps,
      ],
      opts,
    );
  }

  appeal_dispute(
    args: { quest_id: string; initiator: string; new_arbitrator: string },
    opts?: any,
  ): AssembledTransaction<void> {
    return this.c.appeal_dispute(
      [
        args.quest_id,
        new Address(args.initiator),
        new Address(args.new_arbitrator),
      ],
      opts,
    );
  }

  withdraw_dispute(
    args: { quest_id: string; initiator: string },
    opts?: any,
  ): AssembledTransaction<void> {
    return this.c.withdraw_dispute(
      [args.quest_id, new Address(args.initiator)],
      opts,
    );
  }

  get_dispute(
    args: { quest_id: string; initiator: string },
    opts?: any,
  ): AssembledTransaction<Dispute> {
    return this.c.get_dispute(
      [args.quest_id, new Address(args.initiator)],
      opts,
    );
  }

  emergency_pause(
    args: { caller: string },
    opts?: any,
  ): AssembledTransaction<void> {
    return this.c.emergency_pause([new Address(args.caller)], opts);
  }

  emergency_approve_unpause(
    args: { caller: string },
    opts?: any,
  ): AssembledTransaction<void> {
    return this.c.emergency_approve_unpause(
      [new Address(args.caller)],
      opts,
    );
  }

  emergency_unpause(
    args: { caller: string },
    opts?: any,
  ): AssembledTransaction<void> {
    return this.c.emergency_unpause([new Address(args.caller)], opts);
  }

  emergency_withdraw(
    args: { caller: string; asset: string; to: string; amount: bigint },
    opts?: any,
  ): AssembledTransaction<void> {
    return this.c.emergency_withdraw(
      [
        new Address(args.caller),
        new Address(args.asset),
        new Address(args.to),
        args.amount,
      ],
      opts,
    );
  }

  deposit_escrow(
    args: {
      quest_id: string;
      depositor: string;
      token: string;
      amount: bigint;
    },
    opts?: any,
  ): AssembledTransaction<void> {
    return this.c.deposit_escrow(
      [
        args.quest_id,
        new Address(args.depositor),
        new Address(args.token),
        args.amount,
      ],
      opts,
    );
  }

  deposit_verifier_stake(
    args: {
      quest_id: string;
      verifier: string;
      token: string;
      amount: bigint;
    },
    opts?: any,
  ): AssembledTransaction<void> {
    return this.c.deposit_verifier_stake(
      [
        args.quest_id,
        new Address(args.verifier),
        new Address(args.token),
        args.amount,
      ],
      opts,
    );
  }

  return_verifier_stake(
    args: { quest_id: string; verifier: string; caller: string },
    opts?: any,
  ): AssembledTransaction<void> {
    return this.c.return_verifier_stake(
      [args.quest_id, new Address(args.verifier), new Address(args.caller)],
      opts,
    );
  }

  cancel_quest(
    args: { quest_id: string; creator: string },
    opts?: any,
  ): AssembledTransaction<bigint> {
    return this.c.cancel_quest(
      [args.quest_id, new Address(args.creator)],
      opts,
    );
  }

  withdraw_unclaimed(
    args: { quest_id: string; creator: string },
    opts?: any,
  ): AssembledTransaction<bigint> {
    return this.c.withdraw_unclaimed(
      [args.quest_id, new Address(args.creator)],
      opts,
    );
  }

  expire_quest(
    args: { quest_id: string; creator: string },
    opts?: any,
  ): AssembledTransaction<bigint> {
    return this.c.expire_quest(
      [args.quest_id, new Address(args.creator)],
      opts,
    );
  }

  update_quest_metadata(
    args: { quest_id: string; updater: string; metadata: QuestMetadata },
    opts?: any,
  ): AssembledTransaction<void> {
    return this.c.update_quest_metadata(
      [args.quest_id, new Address(args.updater), args.metadata],
      opts,
    );
  }

  get_quest_metadata(
    args: { quest_id: string },
    opts?: any,
  ): AssembledTransaction<QuestMetadata> {
    return this.c.get_quest_metadata([args.quest_id], opts);
  }

  has_quest_metadata(
    args: { quest_id: string },
    opts?: any,
  ): AssembledTransaction<boolean> {
    return this.c.has_quest_metadata([args.quest_id], opts);
  }

  get_escrow_balance(
    args: { quest_id: string },
    opts?: any,
  ): AssembledTransaction<bigint> {
    return this.c.get_escrow_balance([args.quest_id], opts);
  }

  get_escrow_info(
    args: { quest_id: string },
    opts?: any,
  ): AssembledTransaction<EscrowInfo> {
    return this.c.get_escrow_info([args.quest_id], opts);
  }

  get_quest(
    args: { quest_id: string },
    opts?: any,
  ): AssembledTransaction<Quest> {
    return this.c.get_quest([args.quest_id], opts);
  }

  get_submission(
    args: { quest_id: string; submitter: string },
    opts?: any,
  ): AssembledTransaction<Submission> {
    return this.c.get_submission(
      [args.quest_id, new Address(args.submitter)],
      opts,
    );
  }

  set_unpause_threshold(
    args: { caller: string; threshold: number },
    opts?: any,
  ): AssembledTransaction<void> {
    return this.c.set_unpause_threshold(
      [new Address(args.caller), args.threshold],
      opts,
    );
  }

  set_unpause_timelock(
    args: { caller: string; seconds: bigint },
    opts?: any,
  ): AssembledTransaction<void> {
    return this.c.set_unpause_timelock(
      [new Address(args.caller), args.seconds],
      opts,
    );
  }

  get_quests_by_status(
    args: { status: QuestStatus; offset: number; limit: number },
    opts?: any,
  ): AssembledTransaction<Quest[]> {
    return this.c.get_quests_by_status(
      [args.status, args.offset, args.limit],
      opts,
    );
  }

  get_quests_by_creator(
    args: { creator: string; offset: number; limit: number },
    opts?: any,
  ): AssembledTransaction<Quest[]> {
    return this.c.get_quests_by_creator(
      [new Address(args.creator), args.offset, args.limit],
      opts,
    );
  }

  get_active_quests(
    args: { offset: number; limit: number },
    opts?: any,
  ): AssembledTransaction<Quest[]> {
    return this.c.get_active_quests([args.offset, args.limit], opts);
  }

  get_quests_by_reward_range(
    args: {
      min_reward: bigint;
      max_reward: bigint;
      offset: number;
      limit: number;
    },
    opts?: any,
  ): AssembledTransaction<Quest[]> {
    return this.c.get_quests_by_reward_range(
      [args.min_reward, args.max_reward, args.offset, args.limit],
      opts,
    );
  }

  get_platform_stats(opts?: any): AssembledTransaction<PlatformStats> {
    return this.c.get_platform_stats(undefined, opts);
  }

  get_creator_stats(
    args: { creator: string },
    opts?: any,
  ): AssembledTransaction<CreatorStats> {
    return this.c.get_creator_stats([new Address(args.creator)], opts);
  }

  reset_platform_stats(
    args: { caller: string },
    opts?: any,
  ): AssembledTransaction<void> {
    return this.c.reset_platform_stats([new Address(args.caller)], opts);
  }

  add_oracle(
    args: { caller: string; oracle_config: OracleConfig },
    opts?: any,
  ): AssembledTransaction<void> {
    return this.c.add_oracle(
      [new Address(args.caller), args.oracle_config],
      opts,
    );
  }

  remove_oracle(
    args: { caller: string; oracle_address: string },
    opts?: any,
  ): AssembledTransaction<void> {
    return this.c.remove_oracle(
      [new Address(args.caller), new Address(args.oracle_address)],
      opts,
    );
  }

  update_oracle(
    args: { caller: string; oracle_config: OracleConfig },
    opts?: any,
  ): AssembledTransaction<void> {
    return this.c.update_oracle(
      [new Address(args.caller), args.oracle_config],
      opts,
    );
  }

  get_price(
    args: {
      base_asset: string;
      quote_asset: string;
      max_age_seconds: bigint;
    },
    opts?: any,
  ): AssembledTransaction<AggregatedPrice> {
    return this.c.get_price(
      [
        new Address(args.base_asset),
        new Address(args.quote_asset),
        args.max_age_seconds,
      ],
      opts,
    );
  }

  get_price_from_oracle(
    args: {
      oracle_address: string;
      base_asset: string;
      quote_asset: string;
      max_age_seconds: bigint;
    },
    opts?: any,
  ): AssembledTransaction<PriceData> {
    return this.c.get_price_from_oracle(
      [
        new Address(args.oracle_address),
        new Address(args.base_asset),
        new Address(args.quote_asset),
        args.max_age_seconds,
      ],
      opts,
    );
  }

  get_oracle_configs(opts?: any): AssembledTransaction<OracleConfig[]> {
    return this.c.get_oracle_configs(undefined, opts);
  }

  get_active_oracle_configs(opts?: any): AssembledTransaction<OracleConfig[]> {
    return this.c.get_active_oracle_configs(undefined, opts);
  }

  convert_reward_amount(
    args: { from_asset: string; to_asset: string; amount: bigint },
    opts?: any,
  ): AssembledTransaction<bigint> {
    return this.c.convert_reward_amount(
      [
        new Address(args.from_asset),
        new Address(args.to_asset),
        args.amount,
      ],
      opts,
    );
  }

  validate_reward_with_oracle(
    args: {
      reward_asset: string;
      reward_amount: bigint;
      reference_asset: string;
      max_deviation_percent: number;
    },
    opts?: any,
  ): AssembledTransaction<void> {
    return this.c.validate_reward_with_oracle(
      [
        new Address(args.reward_asset),
        args.reward_amount,
        new Address(args.reference_asset),
        args.max_deviation_percent,
      ],
      opts,
    );
  }

  // ── Token Interface (SEP-41) ──

  allowance(
    args: { from: string; spender: string },
    opts?: any,
  ): AssembledTransaction<bigint> {
    return this.c.allowance(
      [new Address(args.from), new Address(args.spender)],
      opts,
    );
  }

  approve(
    args: {
      from: string;
      spender: string;
      amount: bigint;
      expiration_ledger: number;
    },
    opts?: any,
  ): AssembledTransaction<void> {
    return this.c.approve(
      [
        new Address(args.from),
        new Address(args.spender),
        args.amount,
        args.expiration_ledger,
      ],
      opts,
    );
  }

  balance(
    args: { id: string },
    opts?: any,
  ): AssembledTransaction<bigint> {
    return this.c.balance([new Address(args.id)], opts);
  }

  transfer(
    args: { from: string; to: string; amount: bigint },
    opts?: any,
  ): AssembledTransaction<void> {
    return this.c.transfer(
      [new Address(args.from), new Address(args.to), args.amount],
      opts,
    );
  }

  transfer_from(
    args: { spender: string; from: string; to: string; amount: bigint },
    opts?: any,
  ): AssembledTransaction<void> {
    return this.c.transfer_from(
      [
        new Address(args.spender),
        new Address(args.from),
        new Address(args.to),
        args.amount,
      ],
      opts,
    );
  }

  burn(
    args: { from: string; amount: bigint },
    opts?: any,
  ): AssembledTransaction<void> {
    return this.c.burn([new Address(args.from), args.amount], opts);
  }

  burn_from(
    args: { spender: string; from: string; amount: bigint },
    opts?: any,
  ): AssembledTransaction<void> {
    return this.c.burn_from(
      [new Address(args.spender), new Address(args.from), args.amount],
      opts,
    );
  }

  decimals(opts?: any): AssembledTransaction<number> {
    return this.c.decimals(undefined, opts);
  }

  name(opts?: any): AssembledTransaction<string> {
    return this.c.name(undefined, opts);
  }

  symbol(opts?: any): AssembledTransaction<string> {
    return this.c.symbol(undefined, opts);
  }

  mint(
    args: { caller: string; to: string; amount: bigint },
    opts?: any,
  ): AssembledTransaction<void> {
    return this.c.mint(
      [new Address(args.caller), new Address(args.to), args.amount],
      opts,
    );
  }

  set_token_metadata(
    args: { caller: string; name: string; symbol: string; decimals: number },
    opts?: any,
  ): AssembledTransaction<void> {
    return this.c.set_token_metadata(
      [new Address(args.caller), args.name, args.symbol, args.decimals],
      opts,
    );
  }
}
